name: jadwalku
description: "Aplikasi Jadwal Kuliah dan Pengingat Berbasis Android"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
